---@alias loop.TaskType "lua"|"tool"|"app"|"debug"

---@class loop.Task
---@field name string # non-empty task name (supports ${VAR} templates)
---@field type loop.TaskType # task category
---@field command string[]|string # non-empty executable command (supports templates)
---@field cwd string? # optional working directory (supports templates)
---@field env table<string,string>? # optional environment variables
---@field quickfix_matcher string|nil
---@field debugger string|nil
---@field depends_on string[]? # optional list of dependent task names
