---@alias loop.TaskType "vimcmd"|"tool"|"app"|"debug"

---@class loop.Task
---@field name string # non-empty task name (supports ${VAR} templates)
---@field type loop.TaskType # task category
---@field command string[]|string|nil
---@field cwd string?
---@field env table<string,string>? # optional environment variables
---@field quickfix_matcher string|nil
---@field depends_on string[]? # optional list of dependent task names
---@field debug_type "local"|"remote"|nil
---@field debug_adapter string|nil
---@field run_in_terminal boolean|nil
---@field stop_on_entry boolean|nil
---@field debugger_host string|nil
---@field debugger_port number|nil
